In [ ]:
import numpy as np

# Print the numpy version and the configuration 

In [ ]:
print(np.__version__)
np.show_config()

# Create a null vector of size 10

In [ ]:
z=np.zeros(10)
print(z)

# How to get the documentation of the numpy add function from the command line? 

In [3]:
python -c "import numpy; numpy.info(numpy.add)"

SyntaxError: invalid syntax (<ipython-input-3-1663cd30cb7c>, line 1)

# Create a null vector of size 10 but the fifth value which is 1

In [5]:
z=np.zeros(10)
z[4]=1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


# Create a vector with values ranging from 10 to 49 

In [4]:
z=np.arange(10,50)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


# Reverse a vector (first element becomes last)

In [6]:
import numpy as np
z=np.arange(50)
z=z[::-1]
print(z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


# Create a 3x3 matrix with values ranging from 0 to 8

In [7]:
z=np.arange(9).reshape(3,3)
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
z=[[1,2,3],[4,5,66],[8.9,10]]
#print(\n),z
print('\n',z)

# Find indices of non-zero elements from [1,2,0,0,4,0] 

In [8]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


# Create a 3x3 identity matrix 

In [9]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Create a 3x3x3 array with random values

In [10]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.69910038 0.04110676 0.90644348]
  [0.59169625 0.91533088 0.62585046]
  [0.70445798 0.72844066 0.22986016]]

 [[0.97970417 0.84194329 0.16337362]
  [0.82302209 0.7924222  0.8953371 ]
  [0.3716731  0.71241657 0.83034292]]

 [[0.62310816 0.4980791  0.67987271]
  [0.02653848 0.28063536 0.22759136]
  [0.51452482 0.98263782 0.25743219]]]


# Create a 10x10 array with random values and find the minimum and maximum values

In [11]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.004556156696825742 0.9589447405540286


In [12]:
Z = np.random.random((10,10))
Z

array([[0.85683852, 0.46747439, 0.03674437, 0.1857545 , 0.4751129 ,
        0.4652184 , 0.92652204, 0.78370092, 0.41047132, 0.05762736],
       [0.16795106, 0.38541818, 0.66626325, 0.94493529, 0.95682988,
        0.07991626, 0.21839688, 0.96151289, 0.70600615, 0.07664222],
       [0.6233795 , 0.68586726, 0.39302257, 0.89831178, 0.21365565,
        0.56221484, 0.47833234, 0.93136867, 0.08236101, 0.31060135],
       [0.51853412, 0.08823378, 0.79506936, 0.49527159, 0.44999386,
        0.24040525, 0.09379265, 0.7280654 , 0.77298669, 0.09684998],
       [0.04006965, 0.67910859, 0.57550779, 0.7294831 , 0.52474927,
        0.39868888, 0.82811733, 0.74950057, 0.04043379, 0.97725128],
       [0.00992976, 0.19870689, 0.25625607, 0.28592372, 0.04888587,
        0.00593553, 0.12863582, 0.57505048, 0.03417758, 0.60281159],
       [0.45940701, 0.83981177, 0.49376384, 0.9510757 , 0.77575345,
        0.1192874 , 0.96323247, 0.91338138, 0.34968137, 0.78232098],
       [0.19893736, 0.12626716, 0.1763988

# Create a random vector of size 30 and find the mean value

In [13]:
Z = np.random.random(30)
m = Z.mean()
print(Z)
print(m)

[0.07192215 0.3242404  0.80615916 0.86844943 0.38832972 0.78596918
 0.08194733 0.85539961 0.85644942 0.26778428 0.21116731 0.31698032
 0.29429582 0.30147025 0.85254068 0.59252803 0.53765307 0.46214049
 0.59586029 0.7868138  0.44336967 0.90693805 0.02508741 0.24387627
 0.25569497 0.36680789 0.66090902 0.43903945 0.04777885 0.78069558]
0.4809432635729027


# Create a 2d array with 1 on the border and 0 inside

In [8]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
Z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [16]:
Z = np.zeros((10,10))
Z[1:-1,1:-1] = 1
Z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

# What is the result of the following expression?

In [7]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1

False

# Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [14]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [15]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

# Create a 8x8 matrix and fill it with a checkerboard pattern

In [17]:
Z = np.zeros((8,8))
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


# Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element

In [28]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


# Create a checkerboard 8x8 matrix using the tile function

In [18]:
Z = np.tile( np.array([[0,1],[1,0]]), (2,2))
print(Z)

[[0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]]


# Normalize a 5x5 random matrix 

In [30]:
Z = np.random.random((5,5))
print (Z)
Zmax, Zmin = Z.max(), Z.min()
Z = (Z - Zmin)/(Zmax - Zmin)
print(Z)

[[0.02429511 0.58426263 0.35364069 0.10138726 0.45659093]
 [0.89613084 0.55544752 0.55998302 0.83451781 0.96319725]
 [0.06868255 0.11500329 0.10405114 0.06943634 0.58030985]
 [0.71293239 0.15927079 0.0215707  0.72385381 0.34782926]
 [0.64735475 0.64889829 0.00789273 0.62327401 0.91468775]]
[[0.0171698  0.60333631 0.36192435 0.09786883 0.46969128]
 [0.92979578 0.57317303 0.57792074 0.86530009 1.        ]
 [0.06363398 0.11212191 0.10065734 0.06442303 0.59919859]
 [0.7380261  0.15846053 0.01431793 0.74945849 0.35584102]
 [0.6693803  0.67099605 0.         0.6441729  0.9492209 ]]


# Create a custom dtype that describes a color as four unisgned bytes (RGBA)

In [23]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

# Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) 

In [ ]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

# Given a 1D array, negate all elements which are between 3 and 8, in place.

In [24]:
Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

In [ ]:
x=linspace(5,10,num=2)
x

# Consider an integer vector Z, which of these expressions are legal

In [75]:
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

TypeError: ufunc 'left_shift' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

# What are the result of the following expressions?

In [ ]:
np.array(0) // np.array(0)
np.array(0) // np.array(0.)
np.array(0) / np.array(0)
np.array(0) / np.array(0.)

# How to round away from zero a float array ?

In [25]:
Z = np.random.uniform(-10,+10,10)
print (np.trunc(Z + np.copysign(0.5, Z)))

[ 8.  3. -1.  6. 10. -9. -9.  4. -8. 10.]


# Extract the integer part of a random array using 5 different methods 

In [26]:
Z = np.random.uniform(0,10,10)

print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[1. 6. 7. 2. 7. 3. 6. 3. 8. 2.]
[1. 6. 7. 2. 7. 3. 6. 3. 8. 2.]
[1. 6. 7. 2. 7. 3. 6. 3. 8. 2.]
[1 6 7 2 7 3 6 3 8 2]
[1. 6. 7. 2. 7. 3. 6. 3. 8. 2.]


In [27]:
print (np.floor(Z))

[1. 6. 7. 2. 7. 3. 6. 3. 8. 2.]


In [ ]:
Z = np.random.uniform(0,10,10)
Z

In [ ]:
print (np.trunc(Z))

# Create a 5x5 matrix with row values ranging from 0 to 4 

In [74]:
import numpy as np
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [31]:
Z = np.zeros(0,4,shape[5,5])
Z

NameError: name 'shape' is not defined

In [ ]:
Z = np.arange(5)
Z

# Consider a generator function that generates 10 integers and use it to build an array

In [32]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


# Create a vector of size 10 with values ranging from 0 to 1, both excluded

In [33]:
Z = np.linspace(0,1,12,endpoint=True)[1:-1]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [ ]:
Z = np.linspace(0,1,num=10)
print(Z)

In [ ]:
Z = np.linspace(0,5,12,endpoint=True)[1:-1]
print(Z)

# Create a random vector of size 10 and sort it

In [ ]:
Z = np.random.random(10)
Z.sort()
print(Z)

In [ ]:
Z=np.line[1,2,3,4,5,6,7]
Z.sort()
print(Z)

# How to sum a small array faster than np.sum?

In [ ]:
Z = np.arange(10)
np.add.reduce(Z)

# Consider two random array A anb B, check if they are equal 

In [34]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
print(equal)

False


# Make an array immutable (read-only)

In [ ]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

# Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates 

In [ ]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

In [ ]:
x=np.arange(11)
x[:,5]

# Create random vector of size 10 and replace the maximum value by 0

In [ ]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

# Create a structured array with x and y coordinates covering the [0,1]x[0,1] area

In [ ]:
Z = np.zeros((10,10), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,10),
                             np.linspace(0,1,10))
print(Z)

# Given two arrays, X and Y, construct the Cauchy matrix C (Cij = 1/(xi - yj))

In [ ]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

In [ ]:
y=np.eye(5)
y

# Print the minimum and maximum representable value for each numpy scalar type

In [ ]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

# How to print all the values of an array?

In [ ]:
np.set_printoptions(threshold=np.nan)
Z = np.zeros((25,25))
print(Z)

# How to find the closest value (to a given scalar) in an array?

In [ ]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

In [ ]:
v = np.random.uniform(0,100)
v

# Create a structured array representing a position (x,y) and a color (r,g,b)

In [ ]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                   ('y', float, 1)]),
                    ('color',    [ ('r', float, 1),
                                   ('g', float, 1),
                                   ('b', float, 1)])])
print(Z)

In [ ]:
Z = np.ones(10, [ ('position', [ ('x', float, 0),
                                   ('y', float, 0)]),
                    ('color',    [ ('r', int, 0),
                                   ('g', int, 0),
                                   ('b', int, 0)])])
print(Z)

# Consider a random vector with shape (100,2) representing coordinates, find point by point distances

In [ ]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0]), np.atleast_2d(Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

# Consider a random vector with shape (100,2) representing coordinates, find point by point distances

In [ ]:
import scipy
import scipy.spatial
Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

# How to convert a float (32 bits) array into an integer (32 bits) in place

In [6]:
import numpy as np
Z = np.arange(10, dtype=np.int32)
Z = Z.astype(np.float32, copy=False)
print (Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


# How to read the following file

In [9]:
# File content:
# -------------
1,2,3,4,5
6,,,7,8
,,9,10,11
# -------------

Z = np.genfromtxt("missing.dat", delimiter=",")

SyntaxError: invalid syntax (<ipython-input-9-4c8321f65853>, line 4)

# What is the equivalent of enumerate for numpy arrays?

In [10]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [12]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


# Generate a generic 2D Gaussian-like array

In [13]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [15]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
X

array([[-1.        , -0.77777778, -0.55555556, -0.33333333, -0.11111111,
         0.11111111,  0.33333333,  0.55555556,  0.77777778,  1.        ],
       [-1.        , -0.77777778, -0.55555556, -0.33333333, -0.11111111,
         0.11111111,  0.33333333,  0.55555556,  0.77777778,  1.        ],
       [-1.        , -0.77777778, -0.55555556, -0.33333333, -0.11111111,
         0.11111111,  0.33333333,  0.55555556,  0.77777778,  1.        ],
       [-1.        , -0.77777778, -0.55555556, -0.33333333, -0.11111111,
         0.11111111,  0.33333333,  0.55555556,  0.77777778,  1.        ],
       [-1.        , -0.77777778, -0.55555556, -0.33333333, -0.11111111,
         0.11111111,  0.33333333,  0.55555556,  0.77777778,  1.        ],
       [-1.        , -0.77777778, -0.55555556, -0.33333333, -0.11111111,
         0.11111111,  0.33333333,  0.55555556,  0.77777778,  1.        ],
       [-1.        , -0.77777778, -0.55555556, -0.33333333, -0.11111111,
         0.11111111,  0.33333333,  0.55555556

In [34]:
p,q=np.meshgrid(np.linspace(1,5,num=3),np.linspace(1,5,num=3))
print (p)
print (q)

[[1. 3. 5.]
 [1. 3. 5.]
 [1. 3. 5.]]
[[1. 1. 1.]
 [3. 3. 3.]
 [5. 5. 5.]]


In [19]:
p=np.linspace(1,5,num=3)
p

array([1., 3., 5.])

# How to randomly place p elements in a 2D array

In [31]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print (Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


# Subtract the mean of each row of a matrix

In [36]:
X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)
print (Y)

# Older versions of numpy
#Y = X - X.mean(axis=1).reshape(-1, 1)

[[ 0.3552966   0.07506684  0.1785039   0.22909465  0.10772008 -0.29702378
  -0.20660405 -0.46078938 -0.20147884  0.22021397]
 [-0.33792143  0.22186499  0.1345527   0.17122829  0.27581006 -0.22262301
   0.11490968  0.14530541 -0.21966743 -0.28345927]
 [-0.60236249  0.10341078  0.23245573  0.32842133 -0.26385268 -0.21250231
   0.11046165  0.27427181  0.3152317  -0.28553551]
 [ 0.41702087 -0.3775656  -0.16289065 -0.27619611  0.0276702   0.09521887
  -0.35550889 -0.08266173  0.35029368  0.36461935]
 [ 0.33255525  0.50155656 -0.12829193  0.48620026 -0.3636681  -0.22053549
   0.39563732 -0.35796506 -0.36114823 -0.28434059]]


In [40]:
X = np.random.randint(5, 10)
X

8

In [41]:
X = np.randint(5, 10)
X

AttributeError: module 'numpy' has no attribute 'randint'

In [43]:
v=np.random.randint(0, 10) 
v

3

In [46]:
import random
r1 =random.randint(0, 10) 
print("Random number between 0 and 10 is % s" % (r1)) 

Random number between 0 and 10 is 5


In [47]:
X = np.random.rand(5, 10)
X

array([[0.39765281, 0.89106942, 0.10365195, 0.82354838, 0.95145236,
        0.38822961, 0.69173773, 0.72617645, 0.24026646, 0.84039126],
       [0.84743041, 0.1806665 , 0.35309973, 0.84701158, 0.09434507,
        0.00128798, 0.50222661, 0.90956962, 0.63800427, 0.84437157],
       [0.67681902, 0.14588558, 0.06852285, 0.08009835, 0.27762657,
        0.99463015, 0.57610973, 0.0866701 , 0.95227108, 0.49712417],
       [0.11239393, 0.62269565, 0.28298164, 0.84916617, 0.14763049,
        0.83300577, 0.12212292, 0.98091236, 0.73844636, 0.60679195],
       [0.72535094, 0.03486456, 0.51026099, 0.68595312, 0.44636713,
        0.33335214, 0.85793742, 0.86967407, 0.73380959, 0.97043606]])

# How to I sort an array by the nth column

In [48]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[2 0 6]
 [5 4 8]
 [4 2 9]]
[[2 0 6]
 [4 2 9]
 [5 4 8]]


In [52]:
Z = np.random.randint(0,10,(3,3))
Z

array([[6, 8, 5],
       [7, 2, 7],
       [0, 7, 8]])

# How to tell if a given 2D array has null columns

In [53]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

False


# Find the nearest value from a given value in an array

In [54]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.44923226201027855


In [55]:
Z = np.random.uniform(0,1,10)
Z

array([0.66323707, 0.06902881, 0.63444483, 0.18724202, 0.9907859 ,
       0.14301724, 0.04307186, 0.18519934, 0.81077038, 0.46295675])

# Create an array class that has a name attribute

In [56]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


# Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)

In [57]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[3. 3. 3. 6. 1. 2. 3. 1. 6. 2.]


In [59]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
I

array([2, 2, 0, 1, 9, 6, 7, 1, 4, 4, 7, 5, 6, 4, 7, 6, 5, 9, 2, 2])

# How to accumulate elements of a vector (X) to an array (F) based on an index list (I)

In [72]:
X = [1,2,3,4,5,6,50,1]
I = [1,3,9,3,4,1,50,50]
y = np.bincount(I,X)
p = np.bincount(X)
F = np.bincount(I)
print(y)

[ 0.  7.  0.  6.  5.  0.  0.  0.  0.  3.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 51.]


In [66]:
w = np.array([0.3, 0.5, 0.2, 0.7, 1., -0.6]) # weights
x = np.array([0, 1, 1, 2, 2, 2])
z=np.bincount(x,  weights=w)
print(z)

[0.3 0.7 1.1]


# Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors

In [73]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(np.unique(I))

[0 1]


# Considering a four dimensions array, how to get sum over the last two axis at once

In [76]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[54 34 39 55]
 [54 46 39 46]
 [66 56 57 65]]


In [80]:
A = np.random.randint(0,10,(3,4,3,4))
A

array([[[[3, 5, 2, 7],
         [2, 1, 8, 5],
         [9, 8, 6, 5]],

        [[0, 3, 6, 0],
         [4, 8, 2, 4],
         [1, 1, 9, 8]],

        [[2, 5, 7, 7],
         [2, 5, 4, 6],
         [1, 6, 0, 5]],

        [[7, 0, 9, 9],
         [4, 2, 7, 8],
         [1, 7, 9, 2]]],


       [[[8, 7, 9, 0],
         [2, 2, 3, 2],
         [5, 3, 6, 0]],

        [[2, 6, 6, 8],
         [7, 3, 7, 5],
         [9, 1, 0, 6]],

        [[8, 0, 6, 6],
         [6, 8, 6, 3],
         [5, 5, 7, 4]],

        [[2, 2, 9, 6],
         [4, 9, 1, 3],
         [7, 7, 6, 6]]],


       [[[3, 1, 5, 7],
         [0, 7, 2, 9],
         [2, 0, 3, 7]],

        [[2, 3, 7, 7],
         [3, 0, 0, 6],
         [8, 8, 2, 4]],

        [[1, 0, 7, 9],
         [1, 0, 4, 3],
         [8, 4, 4, 2]],

        [[1, 7, 3, 6],
         [2, 9, 0, 7],
         [5, 9, 4, 7]]]])

# Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices

In [81]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.54334866 0.53487252 0.50772645 0.51053123 0.50780497 0.51369697
 0.37528892 0.60736201 0.62196484 0.4281351 ]


In [84]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
#D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_counts

array([12,  6, 15, 11,  9,  9,  6, 13, 11,  8], dtype=int64)

In [85]:
S = np.random.randint(0,10,100)
S

array([8, 1, 4, 2, 4, 8, 4, 2, 0, 5, 0, 3, 5, 2, 4, 5, 0, 4, 7, 2, 3, 1,
       8, 4, 2, 7, 6, 6, 5, 3, 5, 3, 8, 9, 8, 9, 5, 9, 3, 9, 3, 5, 7, 4,
       2, 8, 7, 2, 5, 8, 3, 1, 0, 8, 6, 5, 7, 1, 4, 1, 3, 6, 6, 9, 8, 2,
       6, 1, 0, 1, 4, 5, 9, 1, 1, 8, 0, 8, 7, 0, 3, 5, 8, 1, 5, 7, 8, 2,
       8, 2, 2, 3, 4, 6, 5, 0, 6, 1, 6, 6])

# How to get the diagonal of a dot product?

In [91]:
A=np.array([1,1])
B=np.array([2,2])
y=np.diag(np.dot(A, B))
y


ValueError: Input must be 1- or 2-d.

In [53]:
A=np.array([[1,2,3],[3,4,5]])
A.ndim
A.shape
A.size

6

In [99]:
type(A)

list

In [26]:
import numpy as np
A=np.array([[[[[1,2,3],[3,4,5]]]]])
A.ndim
len(A)

1

# Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value

In [7]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


# Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)

In [13]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


In [52]:
A = np.ones((5,5,3))
A.ndim
A.size

75

In [15]:
A = np.ones((5,5,3))
A

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

# How to swap two rows of an array

In [20]:
A = np.arange(25).reshape(5,5)
A[[0,2]] = A[[2,0]]
print(A)

[[10 11 12 13 14]
 [ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [19]:
A = np.arange(25).reshape(5,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

# Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the triangles

In [21]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 0, 12) ( 0, 15) ( 1, 63) ( 1, 74) (12, 15) (15, 47) (15, 94) (16, 33)
 (16, 49) (18, 23) (18, 35) (23, 35) (27, 46) (27, 53) (33, 49) (37, 59)
 (37, 88) (39, 44) (39, 79) (44, 79) (46, 53) (47, 94) (55, 76) (55, 98)
 (58, 75) (58, 96) (59, 88) (63, 74) (75, 96) (76, 98)]


In [22]:
faces = np.random.randint(0,100,(10,3))
faces

array([[ 0, 22,  4],
       [64, 29, 36],
       [93, 26, 73],
       [42, 27, 90],
       [91, 56, 36],
       [43, 82, 56],
       [47, 91,  0],
       [79, 90, 52],
       [82,  2, 52],
       [32, 53, 16]])

In [24]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F

array([[75, 92],
       [92, 99],
       [99, 75],
       [67, 88],
       [88,  0],
       [ 0, 67],
       [33,  6],
       [ 6,  2],
       [ 2, 33],
       [15, 38],
       [38, 26],
       [26, 15],
       [83, 37],
       [37, 21],
       [21, 83],
       [66, 94],
       [94, 53],
       [53, 66],
       [86, 59],
       [59, 77],
       [77, 86],
       [92, 20],
       [20, 23],
       [23, 92],
       [26, 34],
       [34, 66],
       [66, 26],
       [46, 88],
       [88, 87],
       [87, 46]])

# Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C?

In [27]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


In [29]:
C = np.bincount([1,1,2,3,4,4,6])
len(C)

7

# How to compute averages using a sliding window over an array(Doubt)

In [30]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


In [31]:
def moving_average(a, n=3) 
print(moving_average(a, n=3))

SyntaxError: invalid syntax (<ipython-input-31-a178e42a6066>, line 1)

# Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (Dbt)

In [32]:
def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

NameError: name 'stride_tricks' is not defined

In [33]:
x = np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [34]:
x = np.random.normal(size=10000) + np.arange(10000)
x

array([-6.46921535e-01,  4.78432051e-01,  3.99046479e+00, ...,
        9.99683232e+03,  9.99763114e+03,  9.99814179e+03])

In [36]:
shape = (a.size - window + 1, window)
shape

NameError: name 'a' is not defined

# How to negate a boolean, or to change the sign of a float inplace

In [41]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)
Z

#Z = np.random.uniform(-1.0,1.0,100)
#np.negative(arr, out=arr)

array([0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0])

In [39]:
A = np.random.randint(0,2,5)
A

array([0, 0, 0, 0, 1])

In [42]:
Z = np.random.randint(0,2,100)
Z

array([1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0])

In [43]:
Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)
Z

array([-0.89595163, -0.79140102, -0.68351896, -0.88830483,  0.34492942,
       -0.15580163,  0.2498463 ,  0.00863153, -0.06589134,  0.67524672,
        0.2545885 , -0.31044735,  0.44931535, -0.53697688,  0.37009339,
        0.20206281,  0.02296024, -0.48046882,  0.460329  , -0.15324558,
        0.16745814, -0.62862587,  0.63099265,  0.04615883,  0.02451888,
       -0.20880829, -0.86968585,  0.19918381, -0.73622352,  0.19661898,
       -0.41663925, -0.75405898,  0.66105375, -0.92868501, -0.52372114,
        0.14218881, -0.18074783, -0.9323417 , -0.24205218,  0.24281548,
        0.98156181,  0.4057408 ,  0.5554252 ,  0.80210054,  0.88712584,
       -0.26957127,  0.70517663,  0.90357748,  0.49217747, -0.12443021,
       -0.89179557,  0.43409303, -0.07186447, -0.0812468 ,  0.96573225,
       -0.43365313, -0.75499879, -0.76825093,  0.7840027 , -0.07234765,
        0.7234798 , -0.65308287, -0.44997151,  0.0389286 ,  0.46702399,
        0.64597229,  0.16561677, -0.94869851, -0.59761009, -0.29

# Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])

In [44]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 2.80287819  8.60769189  1.53791877  6.85949174 13.59451948  7.16871274
  3.72273682 16.27266646  3.38895062  8.61048034]


In [45]:
L = (T**2).sum(axis=1)
L

NameError: name 'T' is not defined

In [46]:
P0 = np.random.uniform(-10,10,(10,2))
P0

array([[ 7.47472024, -1.04769704],
       [ 0.0350174 ,  5.02875755],
       [-6.22276782,  7.76112941],
       [ 2.13537571,  9.13174839],
       [-8.00387277, -3.38215681],
       [ 2.77803269,  2.35798283],
       [-7.15977614,  3.81918289],
       [-7.21405589,  9.06367597],
       [ 6.49571129,  2.13601404],
       [-0.81956477, -8.77203339]])

In [51]:
z=np.sum(axis=1)
z

TypeError: sum() missing 1 required positional argument: 'a'

In [55]:
np.sum([[1, 2], [3, 5]], axis=0)

array([4, 7])

In [58]:
np.sum([[1, 2], [3, 5]], axis=1)

array([3, 8])

# Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])

In [61]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print np.array([distance(P0,P1,p_i) for p_i in p])

SyntaxError: invalid syntax (<ipython-input-61-a95b1671db16>, line 11)

# Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a fill value when necessary)

In [62]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[3 9 6 3 6 5 9 6 4 2]
 [0 8 1 8 1 7 9 4 5 7]
 [0 3 1 1 5 4 8 1 9 8]
 [9 9 6 0 3 2 8 9 9 2]
 [4 2 1 3 6 9 3 7 0 8]
 [5 0 4 3 4 1 9 5 1 0]
 [0 9 6 0 8 4 0 1 2 6]
 [3 0 6 3 3 0 2 7 7 7]
 [6 3 5 4 8 6 5 6 6 0]
 [9 9 0 4 6 3 1 8 9 8]]
[[0 0 0 0 0]
 [0 3 9 6 3]
 [0 0 8 1 8]
 [0 0 3 1 1]
 [0 9 9 6 0]]


C:\Users\jaya\Anaconda3\lib\site-packages\ipykernel_launcher.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


In [63]:
Z = np.random.randint(0,10,(10,10))
Z

array([[7, 8, 8, 7, 7, 2, 7, 1, 5, 9],
       [9, 8, 8, 8, 0, 5, 9, 9, 8, 9],
       [1, 4, 8, 6, 0, 2, 8, 1, 1, 0],
       [4, 0, 8, 4, 8, 7, 8, 3, 7, 5],
       [2, 2, 8, 7, 6, 3, 2, 3, 8, 3],
       [0, 7, 8, 2, 2, 3, 3, 6, 9, 5],
       [8, 2, 9, 5, 0, 3, 3, 6, 1, 8],
       [1, 3, 4, 6, 5, 5, 0, 8, 2, 6],
       [3, 4, 2, 6, 9, 2, 1, 8, 4, 5],
       [8, 2, 6, 3, 4, 3, 1, 8, 8, 6]])

# Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]] (Doubt)

In [71]:
Z = np.arange(1,15,dtype=int)
R = Z.stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

AttributeError: 'numpy.ndarray' object has no attribute 'stride_tricks'

# Compute a matrix rank

In [74]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
rank

10

# How to find the most frequent value in an array

In [75]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

8


In [76]:
Z = np.random.randint(0,10,50)
Z

array([8, 6, 3, 7, 9, 5, 4, 3, 3, 0, 7, 0, 4, 6, 7, 0, 1, 8, 4, 3, 9, 2,
       7, 4, 7, 3, 6, 9, 0, 2, 4, 8, 8, 7, 0, 7, 1, 0, 7, 6, 1, 8, 6, 7,
       1, 9, 1, 1, 2, 0])

# Extract all the contiguous 3x3 blocks from a random 10x10 matrix 

In [77]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

NameError: name 'stride_tricks' is not defined

# Create a 2D array subclass such that Z[i,j] == Z[j,i]

In [78]:
 def __setitem__(self, (i,j), value):
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

SyntaxError: invalid syntax (<ipython-input-78-c68d7795eda5>, line 1)

# Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)

In [79]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


In [81]:
p, n = 10, 20
V = np.ones((p,n,1))
V

array([[[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],


In [84]:
V = np.ones((5,3,2))
V

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

# Consider a 16x16 array, how to get the block-sum (block size is 4x4)

In [99]:
Z = np.ones([16,16])
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
S
u=np.arange(0, Z.shape[0], k)
print(u)

[ 0  4  8 12]


In [90]:
Z = np.ones([16,16])
Z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,

In [97]:
x=np.multiply.reduceat([0,1,2,3,4,5,6,7],[0,5])
x

array([  0, 210], dtype=int32)

# How to implement the Game of Life using numpy arrays

In [102]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])
    Print(N)
    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)

NameError: name 'Print' is not defined

# How to get the n largest values of an array 

In [107]:
Z = np.arange(10000)
k=np.random.shuffle(Z)
n = 5
print (Z[np.argpartition(-Z,n)[:n]])

[9998 9997 9999 9995 9996]


# Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) 

In [108]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


In [117]:
grid = np.indices((2, 3))
grid.shape

(2, 2, 3)

In [116]:
y= np.random.randint(0,5,(10,10))
y

array([[0, 1, 3, 4, 1, 4, 3, 0, 4, 4],
       [0, 0, 0, 0, 0, 1, 0, 2, 3, 0],
       [4, 0, 3, 4, 1, 1, 0, 0, 0, 3],
       [2, 2, 3, 1, 0, 0, 0, 1, 3, 3],
       [0, 2, 0, 0, 1, 4, 3, 3, 0, 3],
       [2, 2, 1, 2, 2, 0, 2, 0, 2, 1],
       [3, 3, 3, 3, 4, 0, 2, 2, 2, 3],
       [1, 3, 4, 1, 1, 2, 0, 0, 0, 3],
       [0, 1, 0, 1, 4, 3, 2, 3, 1, 4],
       [3, 2, 4, 0, 4, 0, 1, 2, 1, 2]])

In [118]:
x = np.arange(20).reshape(5, 4)
row, col = np.indices((2, 3))
x[row, col]

array([[0, 1, 2],
       [4, 5, 6]])

In [119]:
x = np.arange(20).reshape(5, 4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

# How to create a record array from a regular array

In [121]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)


[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


# Consider a large vector Z, compute Z to the power of 3 using 3 different methods

In [123]:
x = np.random.rand(5e7)
%timeit np.power(x,3)
#1 loops, best of 3: 574 ms per loop

#%timeit x*x*x
#1 loops, best of 3: 429 ms per loop

#%timeit np.einsum('i,i,i->i',x,x,x)
#1 loops, best of 3: 244 ms per loop

TypeError: 'float' object cannot be interpreted as an integer

In [124]:
x = np.random.rand(5e7)
x

TypeError: 'float' object cannot be interpreted as an integer

# Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B

In [125]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))
C = (A[..., np.newaxis, np.newaxis] == B)
rows = (C.sum(axis=(1,2,3)) >= B.shape[1]).nonzero()[0]
print(rows)

[0 2 4 5]


In [126]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))
print(A)
print(B)

[[4 4 3]
 [0 0 0]
 [0 0 4]
 [1 2 3]
 [0 0 1]
 [3 3 3]
 [2 2 2]
 [0 4 0]]
[[2 1]
 [3 3]]


# Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) 

In [127]:
Z = np.random.randint(0,5,(10,3))
E = np.logical_and.reduce(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(Z)
print(U)

[[2 3 0]
 [3 4 3]
 [0 2 2]
 [2 1 2]
 [4 4 3]
 [4 0 3]
 [0 2 2]
 [4 2 1]
 [0 2 1]
 [0 1 4]]
[[2 3 0]
 [3 4 3]
 [0 2 2]
 [2 1 2]
 [4 4 3]
 [4 0 3]
 [0 2 2]
 [4 2 1]
 [0 2 1]
 [0 1 4]]


# Convert a vector of ints into a matrix binary representation

In [128]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


# Given a two dimensional array, how to extract unique rows

In [129]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 1 1]
 [1 0 0]
 [1 1 0]]


# Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function 

In [130]:
A = np.array([0, 1, 2])
B = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11]])
np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j', A, B)    # np.outer(A, B)

ValueError: operand has more dimensions than subscripts given in einstein sum, but no '...' ellipsis provided to broadcast the extra dimensions.

# Considering a path described by two vectors (X,Y), how to sample it using equidistant samples

In [132]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)
print(x_int,y_int)

[ 0.00000000e+00 -3.73131229e-01 -2.59817608e+00 -3.26212050e+00
 -2.18442687e+00 -2.98929946e-02  2.42923642e+00  4.54913599e+00
  5.92318348e+00  6.35117933e+00  5.82369277e+00  4.46259540e+00
  2.47320794e+00  1.09577220e-01 -2.36575300e+00 -4.71261671e+00
 -6.72701769e+00 -8.25541575e+00 -9.18486120e+00 -9.46381505e+00
 -9.11085788e+00 -8.12875279e+00 -6.63306046e+00 -4.69271059e+00
 -2.44736165e+00 -2.05444585e-02  2.46101146e+00  4.86841760e+00
  7.08937968e+00  9.02539126e+00  1.05948609e+01  1.17357250e+01
  1.24068974e+01  1.25885805e+01  1.22815267e+01  1.15053927e+01
  1.02963689e+01  8.70429550e+00  6.78948686e+00  4.61716636e+00
  2.25853448e+00 -1.98731680e-01 -2.68040566e+00 -5.11543300e+00
 -7.41973991e+00 -9.53891040e+00 -1.14237629e+01 -1.29919305e+01
 -1.42355069e+01 -1.51243232e+01 -1.56061571e+01 -1.57219415e+01
 -1.54217066e+01 -1.47579136e+01 -1.37255236e+01 -1.23634834e+01
 -1.07024632e+01 -8.78327367e+00 -6.65029558e+00 -4.35514246e+00
 -1.94290275e+00  5.28038

# Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n

In [2]:
import numpy as np
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


# How to create a record array from a regular array

In [4]:
import numpy as np
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


# Consider a large vector Z, compute Z to the power of 3 using 3 different methods

In [5]:
x = np.random.rand(5e7)

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

TypeError: 'float' object cannot be interpreted as an integer

# Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? 

In [6]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[2]


# Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) 

In [7]:
Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[4 1 2]
 [1 3 4]
 [4 2 3]
 [0 4 2]
 [3 3 1]
 [0 4 0]
 [4 2 4]
 [4 3 0]
 [1 0 0]
 [4 3 2]]
[[4 1 2]
 [1 3 4]
 [4 2 3]
 [0 4 2]
 [3 3 1]
 [0 4 0]
 [4 2 4]
 [4 3 0]
 [1 0 0]
 [4 3 2]]
[[4 1 2]
 [1 3 4]
 [4 2 3]
 [0 4 2]
 [3 3 1]
 [0 4 0]
 [4 2 4]
 [4 3 0]
 [1 0 0]
 [4 3 2]]


# Convert a vector of ints into a matrix binary representation

In [8]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])


[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [9]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


# Given a two dimensional array, how to extract unique rows?

In [10]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 0]
 [0 0 1]
 [0 1 0]
 [0 1 1]
 [1 0 1]
 [1 1 0]]


In [11]:
uZ = np.unique(Z, axis=0)
print(uZ)

[[0 0 0]
 [0 0 1]
 [0 1 0]
 [0 1 1]
 [1 0 1]
 [1 1 0]]


# Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function 

In [4]:
import numpy as np
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)
x=np.einsum('i->', A)       # np.sum(A)
y=np.einsum('i,i->i', A, B) # A * B
z=np.einsum('i,i', A, B)    # np.inner(A, B)
i=np.einsum('i,j->ij', A, B)    # np.outer(A, B)
print(x,y,z,i)

4.0507552512679075 [0.24767911 0.04808234 0.14726256 0.02058211 0.31074497 0.30929154
 0.32322334 0.32783647 0.73893686 0.00330405] 2.476943327483455 [[0.24767911 0.19059799 0.24999239 0.2207789  0.32202456 0.46711357
  0.36669486 0.43169491 0.43272195 0.07345989]
 [0.06248225 0.04808234 0.06306583 0.05569611 0.08123746 0.1178392
  0.09250648 0.1089041  0.10916319 0.0185318 ]
 [0.14589988 0.11227521 0.14726256 0.13005382 0.18969442 0.27516173
  0.21600827 0.25429773 0.25490272 0.04327288]
 [0.02308988 0.01776849 0.02330554 0.02058211 0.03002073 0.04354665
  0.03418512 0.04024475 0.0403405  0.0068483 ]
 [0.23900362 0.18392189 0.24123588 0.21304565 0.31074497 0.45075192
  0.35385059 0.41657387 0.41756494 0.0708868 ]
 [0.16399663 0.12620131 0.16552833 0.1461851  0.21322324 0.30929154
  0.24280094 0.28583965 0.28651969 0.04864025]
 [0.21831685 0.16800268 0.2203559  0.19460566 0.28384869 0.41173746
  0.32322334 0.38051766 0.38142294 0.06475125]
 [0.18809173 0.14474336 0.18984848 0.16766326 

# Considering a path described by two vectors (X,Y), how to sample it using equidistant samples

In [6]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

# Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n.

In [7]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


# Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means)

In [8]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.11587871  0.23513177]
